version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Asia/Seoul
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: husky
    versions:
    - 5.1.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.4
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.11.0
    - 3.12.0
    - 3.13.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
    - 2.6.1
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: tailwindcss
    versions:
    - 1.9.6
    - 2.0.3
  - dependency-name: gatsby-transformer-json
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.11.0
    - 2.12.0
    - 2.13.0
  - dependency-name: gatsby-plugin-netlify-cms
    versions:
    - 4.10.0
    - 4.9.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
