backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: contents/images
public_folder: /images

collections:
  - label: Post
    name: post
    folder: contents/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Thumbnail Image, name: thumbnail, widget: image }
      - { label: Body, name: body, widget: markdown }
